import { Survey, InvitedOrg } from "@/types/survey";

export const MOCK_SURVEYS: Survey[] = [
  {
    id: "survey-2026-dei-lenox",
    name: "Diversity, Equity, & Inclusion",
    year: 2026,
    hostOrg: "Lenox Park Solutions, Inc.",
    hostContact: "Esteban Fernandez",
    startDate: "Feb 8, 2026",
    targetCloseDate: "Feb 1, 2027",
    status: "active",
    assetClasses: ["Private Equity", "Venture Capital", "Real Assets"],
    privacyLevel: "No information",
    totalInvited: 47,
    submitted: 12,
    inProgress: 8,
    notStarted: 27,
    lastSubmission: "Mar 18, 2026",
    daysRemaining: 313,
    weeklyReportUrl: "#",
  },
  {
    id: "survey-2026-dei-hamilton",
    name: "DEI Manager Assessment",
    year: 2026,
    hostOrg: "Hamilton Lane Advisors",
    hostContact: "Patricia Moore",
    startDate: "Jan 15, 2026",
    targetCloseDate: "Jun 30, 2026",
    status: "active",
    assetClasses: ["Private Credit", "Infrastructure"],
    privacyLevel: "Aggregate only",
    totalInvited: 0,
    submitted: 0,
    inProgress: 0,
    notStarted: 0,
    lastSubmission: null,
    daysRemaining: 96,
    weeklyReportUrl: "#",
  },
  {
    id: "survey-2026-dei-calpers",
    name: "Emerging Manager DEI Survey",
    year: 2026,
    hostOrg: "CalPERS",
    hostContact: "James Okonkwo",
    startDate: "Apr 1, 2026",
    targetCloseDate: "Sep 30, 2026",
    status: "upcoming",
    assetClasses: ["Private Equity", "Real Estate"],
    privacyLevel: "Full disclosure",
    totalInvited: 62,
    submitted: 0,
    inProgress: 0,
    notStarted: 62,
    lastSubmission: null,
    daysRemaining: null,
    weeklyReportUrl: "#",
  },
  {
    id: "survey-2025-dei-lenox",
    name: "Diversity, Equity, & Inclusion",
    year: 2025,
    hostOrg: "Lenox Park Solutions, Inc.",
    hostContact: "Esteban Fernandez",
    startDate: "Feb 5, 2025",
    targetCloseDate: "Jan 31, 2026",
    status: "closed",
    assetClasses: ["Private Equity", "Venture Capital", "Real Assets"],
    privacyLevel: "No information",
    totalInvited: 41,
    submitted: 38,
    inProgress: 0,
    notStarted: 3,
    lastSubmission: "Jan 28, 2026",
    daysRemaining: 0,
    weeklyReportUrl: "#",
  },
  {
    id: "survey-2025-dei-kkr",
    name: "Workforce Diversity Assessment",
    year: 2025,
    hostOrg: "KKR & Co.",
    hostContact: "Sarah Chen",
    startDate: "Mar 1, 2025",
    targetCloseDate: "Nov 30, 2025",
    status: "closed",
    assetClasses: ["Private Equity", "Infrastructure", "Real Estate"],
    privacyLevel: "Aggregate only",
    totalInvited: 88,
    submitted: 71,
    inProgress: 0,
    notStarted: 17,
    lastSubmission: "Nov 29, 2025",
    daysRemaining: 0,
    weeklyReportUrl: "#",
  },
];

export const MOCK_ORGS: InvitedOrg[] = [
  {
    id: "org-blackstone",
    surveyId: "survey-2026-dei-lenox",
    name: "Blackstone Group",
    type: "GP",
    contactName: "Michael Davis",
    contactTitle: "Chief Diversity & Inclusion Officer",
    contactEmail: "m.davis@blackstone.com",
    invitedDate: "Feb 8, 2026",
    submissionDate: "Mar 10, 2026",
    lastActivity: "Mar 10, 2026",
    status: "submitted",
    progress: 100,
    assetClass: "Private Equity",
    strategyFocus: ["Buyout", "Real Estate", "Credit", "Infrastructure"],
    aum: "$1.0T",
    aumRaw: 1000,
    founded: "1985",
    headquarters: "New York, NY",
    location: "New York, NY",
    lpiScore: 8.2,
    lpiVersion: "v3.1",

    // ── Sub-components: exactly matching the reference image ──────────────
    lpiSubComponents: {
      overall: {
        ownership:  { label: "Ownership Score",  rawScore: 0.44, maxScore: 6.00, percentile: 60 },
        leadership: { label: "Leadership Score",  rawScore: 0.00, maxScore: 2.00, percentile: null },
        workforce:  { label: "Workforce Score",   rawScore: 0.33, maxScore: 2.00, percentile: 11 },
      },
      dimensions: [
        {
          dimension: "Gender",
          color: "#6366f1",   // indigo
          ownership:  { label: "Gender Ownership Score",   rawScore: 0.44, maxScore: 3.00, percentile: 81 },
          leadership: { label: "Gender Leadership Score",  rawScore: 0.00, maxScore: 1.00, percentile: null },
          workforce:  { label: "Gender Workforce Score",   rawScore: 0.33, maxScore: 1.00, percentile: 40 },
        },
        {
          dimension: "Racial",
          color: "#f59e0b",   // amber
          ownership:  { label: "Racial Ownership Score",   rawScore: 0.00, maxScore: 3.00, percentile: null },
          leadership: { label: "Racial Leadership Score",  rawScore: 0.00, maxScore: 1.00, percentile: null },
          workforce:  { label: "Racial Workforce Score",   rawScore: 0.00, maxScore: 1.00, percentile: null },
        },
      ],
      peerGroups: [
        { label: "$AUM",       sublabel: "No AUM Reported",  percentile: 30 },
        { label: "HQ Region",  sublabel: "International",    percentile: 34 },
      ],
    },

    benchmarks: {
      universe: {
        label: "Roundtables Universe",
        p10: 4.2, q1: 5.8, median: 6.9, q3: 8.0, p90: 9.1,
        min: 2.1, max: 10.0,
        managerValue: 8.2, managerPercentile: 72, n: 312,
      },
      portfolio: {
        label: "My Portfolio",
        p10: 5.1, q1: 6.4, median: 7.2, q3: 8.3, p90: 9.3,
        min: 3.8, max: 9.8,
        managerValue: 8.2, managerPercentile: 61, n: 47,
      },
      assetClass: {
        label: "Asset Class (Private Equity)",
        p10: 4.8, q1: 6.1, median: 7.0, q3: 8.1, p90: 9.2,
        min: 2.9, max: 10.0,
        managerValue: 8.2, managerPercentile: 68, n: 89,
        comingSoon: true,
      },
    },
    genderDemographics: {
      ownership:  { men: 13, women: 4 },
      leadership: { men: 9,  women: 0 },
      workforce:  { men: 12, women: 6 },
    },
    racialDemographics: {
      ownership: {
        indigenous_na:  0,
        asian:          2,
        black:          1,
        latino:         0,
        mena:           0,
        indigenous_out: 0,
        white:          13,
        other:          1,
        multiracial:    0,
      },
      leadership: {
        indigenous_na:  0,
        asian:          1,
        black:          0,
        latino:         1,
        mena:           0,
        indigenous_out: 0,
        white:          7,
        other:          0,
        multiracial:    0,
      },
      workforce: {
        indigenous_na:  0,
        asian:          3,
        black:          2,
        latino:         1,
        mena:           1,
        indigenous_out: 0,
        white:          10,
        other:          1,
        multiracial:    0,
      },
    },
  },

  {
    id: "org-kkr",
    surveyId: "survey-2026-dei-lenox",
    name: "KKR & Co.",
    type: "GP",
    contactName: "Jennifer Walsh",
    contactTitle: "Head of Human Capital",
    contactEmail: "j.walsh@kkr.com",
    invitedDate: "Feb 8, 2026",
    submissionDate: "Mar 18, 2026",
    lastActivity: "Mar 18, 2026",
    status: "submitted",
    progress: 100,
    assetClass: "Private Equity",
    strategyFocus: ["Buyout", "Growth Equity", "Credit"],
    aum: "$510B",
    aumRaw: 510,
    founded: "1976",
    headquarters: "New York, NY",
    location: "New York, NY",
    lpiScore: 7.8,
    lpiVersion: "v3.1",

    lpiSubComponents: {
      overall: {
        ownership:  { label: "Ownership Score",  rawScore: 0.67, maxScore: 6.00, percentile: 71 },
        leadership: { label: "Leadership Score",  rawScore: 0.25, maxScore: 2.00, percentile: 44 },
        workforce:  { label: "Workforce Score",   rawScore: 0.58, maxScore: 2.00, percentile: 38 },
      },
      dimensions: [
        {
          dimension: "Gender",
          color: "#6366f1",
          ownership:  { label: "Gender Ownership Score",  rawScore: 0.50, maxScore: 3.00, percentile: 74 },
          leadership: { label: "Gender Leadership Score", rawScore: 0.25, maxScore: 1.00, percentile: 55 },
          workforce:  { label: "Gender Workforce Score",  rawScore: 0.42, maxScore: 1.00, percentile: 48 },
        },
        {
          dimension: "Racial",
          color: "#f59e0b",
          ownership:  { label: "Racial Ownership Score",  rawScore: 0.17, maxScore: 3.00, percentile: 30 },
          leadership: { label: "Racial Leadership Score", rawScore: 0.00, maxScore: 1.00, percentile: null },
          workforce:  { label: "Racial Workforce Score",  rawScore: 0.16, maxScore: 1.00, percentile: 22 },
        },
      ],
      peerGroups: [
        { label: "$AUM",      sublabel: "$250B–$750B",  percentile: 58 },
        { label: "HQ Region", sublabel: "Northeast US", percentile: 61 },
      ],
    },

    benchmarks: {
      universe: {
        label: "Roundtables Universe",
        p10: 4.2, q1: 5.8, median: 6.9, q3: 8.0, p90: 9.1,
        min: 2.1, max: 10.0,
        managerValue: 7.8, managerPercentile: 58, n: 312,
      },
      portfolio: {
        label: "My Portfolio",
        p10: 5.1, q1: 6.4, median: 7.2, q3: 8.3, p90: 9.3,
        min: 3.8, max: 9.8,
        managerValue: 7.8, managerPercentile: 44, n: 47,
      },
      assetClass: {
        label: "Asset Class (Private Equity)",
        p10: 4.8, q1: 6.1, median: 7.0, q3: 8.1, p90: 9.2,
        min: 2.9, max: 10.0,
        managerValue: 7.8, managerPercentile: 54, n: 89,
        comingSoon: true,
      },
    },

    genderDemographics: {
      ownership:  { men: 8,  women: 4 },
      leadership: { men: 11, women: 3 },
      workforce:  { men: 19, women: 14 },
    },
    racialDemographics: {
      ownership: {
        indigenous_na: 0, asian: 2, black: 1, latino: 1, mena: 0,
        indigenous_out: 0, white: 8, other: 0, multiracial: 0,
      },
      leadership: {
        indigenous_na: 0, asian: 2, black: 0, latino: 0, mena: 1,
        indigenous_out: 0, white: 11, other: 0, multiracial: 0,
      },
      workforce: {
        indigenous_na: 0, asian: 5, black: 3, latino: 2, mena: 1,
        indigenous_out: 0, white: 19, other: 2, multiracial: 1,
      },
    },
  },

  {
    id: "org-apollo",
    surveyId: "survey-2026-dei-lenox",
    name: "Apollo Global Management",
    type: "GP",
    contactName: "Robert Kim",
    contactTitle: "Managing Director, DEI",
    contactEmail: "r.kim@apollo.com",
    invitedDate: "Feb 8, 2026",
    submissionDate: null,
    lastActivity: "Feb 22, 2026",
    status: "in_progress",
    progress: 64,
    assetClass: "Private Credit",
    strategyFocus: ["Credit", "Private Equity", "Real Assets"],
    aum: "$651B",
    aumRaw: 651,
    founded: "1990",
    headquarters: "New York, NY",
    location: "New York, NY",
    lpiScore: null,
    lpiVersion: "v3.1",
    lpiSubComponents: null,
    benchmarks: null,
    genderDemographics: null,
    racialDemographics: null,
  },

  {
    id: "org-carlyle",
    surveyId: "survey-2026-dei-lenox",
    name: "The Carlyle Group",
    type: "GP",
    contactName: "Amanda Torres",
    contactTitle: "VP, Diversity & Inclusion",
    contactEmail: "a.torres@carlyle.com",
    invitedDate: "Feb 8, 2026",
    submissionDate: null,
    lastActivity: "Mar 5, 2026",
    status: "in_progress",
    progress: 41,
    assetClass: "Private Equity",
    strategyFocus: ["Buyout", "Growth Capital", "Infrastructure"],
    aum: "$426B",
    aumRaw: 426,
    founded: "1987",
    headquarters: "Washington, DC",
    location: "Washington, DC",
    lpiScore: null,
    lpiVersion: "v3.1",
    lpiSubComponents: null,
    benchmarks: null,
    genderDemographics: null,
    racialDemographics: null,
  },

  {
    id: "org-tpg",
    surveyId: "survey-2026-dei-lenox",
    name: "TPG Capital",
    type: "GP",
    contactName: "Chris Lee",
    contactTitle: "Director, Human Resources",
    contactEmail: "c.lee@tpg.com",
    invitedDate: "Feb 8, 2026",
    submissionDate: null,
    lastActivity: null,
    status: "not_started",
    progress: 0,
    assetClass: "Private Equity",
    strategyFocus: ["Buyout", "Growth", "Impact"],
    aum: "$222B",
    aumRaw: 222,
    founded: "1992",
    headquarters: "Fort Worth, TX",
    location: "Fort Worth, TX",
    lpiScore: null,
    lpiVersion: "v3.1",
    lpiSubComponents: null,
    benchmarks: null,
    genderDemographics: null,
    racialDemographics: null,
  },

  {
    id: "org-vista",
    surveyId: "survey-2026-dei-lenox",
    name: "Vista Equity Partners",
    type: "GP",
    contactName: "Nicole Brown",
    contactTitle: "Chief People Officer",
    contactEmail: "n.brown@vistaequitypartners.com",
    invitedDate: "Feb 8, 2026",
    submissionDate: null,
    lastActivity: null,
    status: "not_started",
    progress: 0,
    assetClass: "Venture Capital",
    strategyFocus: ["Software Buyout", "Growth Equity"],
    aum: "$101B",
    aumRaw: 101,
    founded: "2000",
    headquarters: "Austin, TX",
    location: "Austin, TX",
    lpiScore: null,
    lpiVersion: "v3.1",
    lpiSubComponents: null,
    benchmarks: null,
    genderDemographics: null,
    racialDemographics: null,
  },

  {
    id: "org-bain",
    surveyId: "survey-2026-dei-lenox",
    name: "Bain Capital",
    type: "GP",
    contactName: "Thomas Grant",
    contactTitle: "Partner, Talent & Culture",
    contactEmail: "t.grant@baincapital.com",
    invitedDate: "Feb 8, 2026",
    submissionDate: "Mar 1, 2026",
    lastActivity: "Mar 1, 2026",
    status: "submitted",
    progress: 100,
    assetClass: "Private Equity",
    strategyFocus: ["Buyout", "Venture", "Credit"],
    aum: "$185B",
    aumRaw: 185,
    founded: "1984",
    headquarters: "Boston, MA",
    location: "Boston, MA",
    lpiScore: 7.1,
    lpiVersion: "v3.1",

    lpiSubComponents: {
      overall: {
        ownership:  { label: "Ownership Score",  rawScore: 0.22, maxScore: 6.00, percentile: 31 },
        leadership: { label: "Leadership Score",  rawScore: 0.11, maxScore: 2.00, percentile: 18 },
        workforce:  { label: "Workforce Score",   rawScore: 0.44, maxScore: 2.00, percentile: 29 },
      },
      dimensions: [
        {
          dimension: "Gender",
          color: "#6366f1",
          ownership:  { label: "Gender Ownership Score",  rawScore: 0.22, maxScore: 3.00, percentile: 40 },
          leadership: { label: "Gender Leadership Score", rawScore: 0.11, maxScore: 1.00, percentile: 24 },
          workforce:  { label: "Gender Workforce Score",  rawScore: 0.33, maxScore: 1.00, percentile: 35 },
        },
        {
          dimension: "Racial",
          color: "#f59e0b",
          ownership:  { label: "Racial Ownership Score",  rawScore: 0.00, maxScore: 3.00, percentile: null },
          leadership: { label: "Racial Leadership Score", rawScore: 0.00, maxScore: 1.00, percentile: null },
          workforce:  { label: "Racial Workforce Score",  rawScore: 0.11, maxScore: 1.00, percentile: 15 },
        },
      ],
      peerGroups: [
        { label: "$AUM",      sublabel: "$100B–$250B",  percentile: 42 },
        { label: "HQ Region", sublabel: "Northeast US", percentile: 38 },
      ],
    },

    benchmarks: {
      universe: {
        label: "Roundtables Universe",
        p10: 4.2, q1: 5.8, median: 6.9, q3: 8.0, p90: 9.1,
        min: 2.1, max: 10.0,
        managerValue: 7.1, managerPercentile: 43, n: 312,
      },
      portfolio: {
        label: "My Portfolio",
        p10: 5.1, q1: 6.4, median: 7.2, q3: 8.3, p90: 9.3,
        min: 3.8, max: 9.8,
        managerValue: 7.1, managerPercentile: 31, n: 47,
      },
      assetClass: {
        label: "Asset Class (Private Equity)",
        p10: 4.8, q1: 6.1, median: 7.0, q3: 8.1, p90: 9.2,
        min: 2.9, max: 10.0,
        managerValue: 7.1, managerPercentile: 37, n: 89,
        comingSoon: true,
      },
    },

    genderDemographics: {
      ownership:  { men: 14, women: 3 },
      leadership: { men: 10, women: 2 },
      workforce:  { men: 22, women: 11 },
    },
    racialDemographics: {
      ownership: {
        indigenous_na: 0, asian: 1, black: 0, latino: 0, mena: 0,
        indigenous_out: 0, white: 16, other: 0, multiracial: 0,
      },
      leadership: {
        indigenous_na: 0, asian: 1, black: 1, latino: 0, mena: 0,
        indigenous_out: 0, white: 10, other: 0, multiracial: 0,
      },
      workforce: {
        indigenous_na: 0, asian: 4, black: 2, latino: 1, mena: 0,
        indigenous_out: 0, white: 24, other: 1, multiracial: 1,
      },
    },
  },

  {
    id: "org-warburg",
    surveyId: "survey-2026-dei-lenox",
    name: "Warburg Pincus",
    type: "GP",
    contactName: "Lisa Park",
    contactTitle: "Managing Director",
    contactEmail: "l.park@warburgpincus.com",
    invitedDate: "Feb 8, 2026",
    submissionDate: null,
    lastActivity: "Feb 15, 2026",
    status: "in_progress",
    progress: 22,
    assetClass: "Venture Capital",
    strategyFocus: ["Growth Equity", "Venture"],
    aum: "$83B",
    aumRaw: 83,
    founded: "1966",
    headquarters: "New York, NY",
    location: "New York, NY",
    lpiScore: null,
    lpiVersion: "v3.1",
    lpiSubComponents: null,
    benchmarks: null,
    genderDemographics: null,
    racialDemographics: null,
  },
];

export function getSurveyById(id: string): Survey | undefined {
  return MOCK_SURVEYS.find((s) => s.id === id);
}

export function getOrgsBySurveyId(surveyId: string): InvitedOrg[] {
  return MOCK_ORGS.filter((o) => o.surveyId === surveyId);
}

export function getOrgById(id: string): InvitedOrg | undefined {
  return MOCK_ORGS.find((o) => o.id === id);
}

// Gender demographics are exported separately for Blackstone
export const BLACKSTONE_GENDER_DEMOGRAPHICS = {
  ownership: { men: 13, women: 4 },
  leadership: { men: 9, women: 0 },
  workforce: { men: 12, women: 6 },
};
