import { PortfolioManager } from "@/types/portfolio";

export const MOCK_PORTFOLIO_MANAGERS: PortfolioManager[] = [
  {
    id: "pm-blackstone",
    orgId: "org-blackstone",
    name: "Blackstone Group",
    contactName: "Michael Davis",
    contactEmail: "m.davis@blackstone.com",
    contactTitle: "Chief Diversity & Inclusion Officer",
    assetClass: "Private Equity",
    strategy: ["Buyout", "Real Estate", "Credit"],
    location: "New York, NY",
    aum: "$1.0T",
    aumRaw: 1000,
    founded: "1985",
    addedDate: "Jan 12, 2024",
    lpiScore: 8.2,
    tags: ["core", "flagship"],
    funds: [
      {
        id: "f-bcp9",
        managerId: "pm-blackstone",
        name: "Blackstone Capital Partners IX",
        vintage: 2021,
        strategy: "Large-Cap Buyout",
        commitment: 150,
        called: 62,
        nav: 174,
        dpi: 0.08,
        tvpi: 1.24,
        status: "active",
        geography: "North America",
      },
      {
        id: "f-brep10",
        managerId: "pm-blackstone",
        name: "Blackstone Real Estate Partners X",
        vintage: 2022,
        strategy: "Real Estate",
        commitment: 100,
        called: 44,
        nav: 108,
        dpi: 0.00,
        tvpi: 1.09,
        status: "active",
        geography: "Global",
      },
    ],
  },
  {
    id: "pm-kkr",
    orgId: "org-kkr",
    name: "KKR & Co.",
    contactName: "Jennifer Walsh",
    contactEmail: "j.walsh@kkr.com",
    contactTitle: "Head of Human Capital",
    assetClass: "Private Equity",
    strategy: ["Buyout", "Growth Equity", "Infrastructure"],
    location: "New York, NY",
    aum: "$510B",
    aumRaw: 510,
    founded: "1976",
    addedDate: "Jan 12, 2024",
    lpiScore: 7.8,
    tags: ["core"],
    funds: [
      {
        id: "f-kkr-am13",
        managerId: "pm-kkr",
        name: "KKR Americas Fund XIII",
        vintage: 2021,
        strategy: "Large-Cap Buyout",
        commitment: 75,
        called: 58,
        nav: 91,
        dpi: 0.12,
        tvpi: 1.33,
        status: "active",
        geography: "North America",
      },
      {
        id: "f-kkr-infra4",
        managerId: "pm-kkr",
        name: "KKR Global Infrastructure IV",
        vintage: 2020,
        strategy: "Infrastructure",
        commitment: 50,
        called: 80,
        nav: 72,
        dpi: 0.31,
        tvpi: 1.45,
        status: "harvesting",
        geography: "Global",
      },
    ],
  },
  {
    id: "pm-apollo",
    orgId: "org-apollo",
    name: "Apollo Global Management",
    contactName: "Robert Kim",
    contactEmail: "r.kim@apollo.com",
    contactTitle: "Managing Director, DEI",
    assetClass: "Private Credit",
    strategy: ["Credit", "Private Equity"],
    location: "New York, NY",
    aum: "$651B",
    aumRaw: 651,
    founded: "1990",
    addedDate: "Mar 5, 2024",
    lpiScore: null,
    tags: ["credit-focus"],
    funds: [
      {
        id: "f-apollo-10",
        managerId: "pm-apollo",
        name: "Apollo Investment Fund X",
        vintage: 2022,
        strategy: "Hybrid Value",
        commitment: 100,
        called: 35,
        nav: 107,
        dpi: 0.00,
        tvpi: 1.07,
        status: "active",
        geography: "North America",
      },
      {
        id: "f-apollo-ssl4",
        managerId: "pm-apollo",
        name: "Apollo Senior Secured Loan Program IV",
        vintage: 2023,
        strategy: "Private Credit",
        commitment: 75,
        called: 21,
        nav: 76,
        dpi: 0.04,
        tvpi: 1.05,
        status: "active",
        geography: "North America",
      },
    ],
  },
  {
    id: "pm-sequoia",
    name: "Sequoia Capital",
    contactName: "Priya Nair",
    contactEmail: "p.nair@sequoiacap.com",
    contactTitle: "Venture Partner",
    assetClass: "Venture Capital",
    strategy: ["Seed", "Early Stage", "Growth"],
    location: "Menlo Park, CA",
    aum: "$85B",
    aumRaw: 85,
    founded: "1972",
    addedDate: "Jun 20, 2024",
    lpiScore: null,
    tags: ["emerging-tech"],
    funds: [
      {
        id: "f-seq-gg4",
        managerId: "pm-sequoia",
        name: "Sequoia Capital Global Growth Fund IV",
        vintage: 2021,
        strategy: "Growth Equity",
        commitment: 50,
        called: 72,
        nav: 71,
        dpi: 0.18,
        tvpi: 1.42,
        status: "active",
        geography: "Global",
      },
    ],
  },
  {
    id: "pm-a16z",
    name: "Andreessen Horowitz",
    contactName: "Marcus Webb",
    contactEmail: "m.webb@a16z.com",
    contactTitle: "General Partner",
    assetClass: "Venture Capital",
    strategy: ["Early Stage", "Bio", "Crypto"],
    location: "Menlo Park, CA",
    aum: "$42B",
    aumRaw: 42,
    founded: "2009",
    addedDate: "Aug 14, 2024",
    lpiScore: null,
    tags: ["emerging-tech", "bio"],
    funds: [
      {
        id: "f-a16z-7",
        managerId: "pm-a16z",
        name: "a16z Fund VII",
        vintage: 2022,
        strategy: "Venture",
        commitment: 40,
        called: 48,
        nav: 44,
        dpi: 0.00,
        tvpi: 1.10,
        status: "active",
        geography: "North America",
      },
      {
        id: "f-a16z-bio3",
        managerId: "pm-a16z",
        name: "a16z Bio Fund III",
        vintage: 2022,
        strategy: "Bio/Life Sciences",
        commitment: 25,
        called: 40,
        nav: 27,
        dpi: 0.00,
        tvpi: 1.08,
        status: "active",
        geography: "North America",
      },
    ],
  },
  {
    id: "pm-brookfield",
    name: "Brookfield Asset Management",
    contactName: "Sandra Okafor",
    contactEmail: "s.okafor@brookfield.com",
    contactTitle: "Managing Partner, Infrastructure",
    assetClass: "Real Assets",
    strategy: ["Infrastructure", "Renewable Energy", "Real Estate"],
    location: "Toronto, Canada",
    aum: "$900B",
    aumRaw: 900,
    founded: "1899",
    addedDate: "Jan 12, 2024",
    lpiScore: null,
    tags: ["core", "esg"],
    funds: [
      {
        id: "f-bif5",
        managerId: "pm-brookfield",
        name: "Brookfield Infrastructure Fund V",
        vintage: 2021,
        strategy: "Infrastructure",
        commitment: 100,
        called: 65,
        nav: 119,
        dpi: 0.15,
        tvpi: 1.38,
        status: "active",
        geography: "Global",
      },
      {
        id: "f-brp3",
        managerId: "pm-brookfield",
        name: "Brookfield Renewable Partners III",
        vintage: 2020,
        strategy: "Renewable Energy",
        commitment: 60,
        called: 90,
        nav: 82,
        dpi: 0.42,
        tvpi: 1.65,
        status: "harvesting",
        geography: "Global",
      },
    ],
  },
  {
    id: "pm-vista",
    orgId: "org-vista",
    name: "Vista Equity Partners",
    contactName: "Nicole Brown",
    contactEmail: "n.brown@vistaequitypartners.com",
    contactTitle: "Chief People Officer",
    assetClass: "Private Equity",
    strategy: ["Software Buyout", "Growth Equity"],
    location: "Austin, TX",
    aum: "$101B",
    aumRaw: 101,
    founded: "2000",
    addedDate: "Oct 3, 2024",
    lpiScore: null,
    tags: ["tech-focused"],
    funds: [
      {
        id: "f-vep8",
        managerId: "pm-vista",
        name: "Vista Equity Partners Fund VIII",
        vintage: 2022,
        strategy: "Enterprise Software Buyout",
        commitment: 75,
        called: 30,
        nav: 77,
        dpi: 0.00,
        tvpi: 1.03,
        status: "active",
        geography: "North America",
      },
    ],
  },
  {
    id: "pm-ares",
    name: "Ares Management",
    contactName: "David Fernandez",
    contactEmail: "d.fernandez@aresmgmt.com",
    contactTitle: "Partner, Investor Relations",
    assetClass: "Private Credit",
    strategy: ["Senior Debt", "Mezzanine", "Private Equity"],
    location: "Los Angeles, CA",
    aum: "$428B",
    aumRaw: 428,
    founded: "1997",
    addedDate: "Feb 28, 2025",
    lpiScore: null,
    tags: ["credit-focus"],
    funds: [
      {
        id: "f-ares-corp6",
        managerId: "pm-ares",
        name: "Ares Corporate Opportunities Fund VI",
        vintage: 2022,
        strategy: "Opportunistic Credit",
        commitment: 80,
        called: 42,
        nav: 86,
        dpi: 0.06,
        tvpi: 1.14,
        status: "active",
        geography: "North America",
      },
      {
        id: "f-ares-eu5",
        managerId: "pm-ares",
        name: "Ares Capital Europe V",
        vintage: 2021,
        strategy: "Senior Secured Lending",
        commitment: 50,
        called: 78,
        nav: 61,
        dpi: 0.28,
        tvpi: 1.40,
        status: "harvesting",
        geography: "Europe",
      },
    ],
  },
  {
    id: "pm-general-atlantic",
    name: "General Atlantic",
    contactName: "Tanya Rivers",
    contactEmail: "t.rivers@generalatlantic.com",
    contactTitle: "Managing Director",
    assetClass: "Venture Capital",
    strategy: ["Growth Equity", "Technology", "Healthcare"],
    location: "New York, NY",
    aum: "$84B",
    aumRaw: 84,
    founded: "1980",
    addedDate: "Nov 15, 2024",
    lpiScore: null,
    tags: ["growth"],
    funds: [
      {
        id: "f-ga-2023",
        managerId: "pm-general-atlantic",
        name: "General Atlantic Growth Fund 2023",
        vintage: 2023,
        strategy: "Global Growth Equity",
        commitment: 60,
        called: 18,
        nav: 61,
        dpi: 0.00,
        tvpi: 1.02,
        status: "active",
        geography: "Global",
      },
    ],
  },
];

export function getTotalCommitted(managers: PortfolioManager[]): number {
  return managers.reduce(
    (sum, m) => sum + m.funds.reduce((s, f) => s + f.commitment, 0),
    0
  );
}

export function getTotalFunds(managers: PortfolioManager[]): number {
  return managers.reduce((sum, m) => sum + m.funds.length, 0);
}

export const ASSET_CLASSES = [
  "Private Equity",
  "Venture Capital",
  "Private Credit",
  "Real Assets",
  "Infrastructure",
  "Real Estate",
];
