import type {
  SupportTicket,
  QuickReplyTemplate,
  WalkthroughStep,
  TicketStatus,
  TicketType,
  TemplateCategory,
} from "@/types/support";

// ─── Tickets ─────────────────────────────────────────────────────────────────

export const MOCK_TICKETS: SupportTicket[] = [
  // ── Permissions (5 × High) ──────────────────────────────────────────────
  {
    id: "TKT-0001",
    type: "Permissions",
    status: "New",
    priority: "High",
    subject: "Cannot access survey — permission denied error",
    requesterName: "Michael Davis",
    requesterEmail: "m.davis@blackstone.com",
    requesterOrg: "Blackstone Group",
    requesterOrgType: "GP",
    createdAt: "2026-03-20T09:14:00Z",
    updatedAt: "2026-03-20T10:05:00Z",
    assignedTo: null,
    surveyId: "survey-001",
    tags: ["permissions", "access-denied"],
    messages: [
      {
        id: "msg-0001-1",
        author: "Michael Davis",
        role: "requester",
        body: "Hi, I'm getting a 'Permission Denied' error when I click the survey link in the invitation email. This started happening yesterday afternoon. My email is m.davis@blackstone.com. Please advise.",
        timestamp: "2026-03-20T09:14:00Z",
        isInternalNote: false,
      },
      {
        id: "msg-0001-2",
        author: "Esteban Fernandez",
        role: "admin",
        body: "Hi Michael — thanks for reaching out. I can see your account in our system. It looks like your role assignment needs to be refreshed. I'm making that change now and you should be able to access the survey within 15 minutes. Let me know if the issue persists.",
        timestamp: "2026-03-20T10:02:00Z",
        isInternalNote: false,
      },
      {
        id: "msg-0001-3",
        author: "Esteban Fernandez",
        role: "admin",
        body: "Checked Blackstone account — role was set to LP instead of GP. Fixed. Monitor for 24 hours before closing.",
        timestamp: "2026-03-20T10:05:00Z",
        isInternalNote: true,
      },
    ],
  },
  {
    id: "TKT-0002",
    type: "Permissions",
    status: "In Review",
    priority: "High",
    subject: "SSO login loops back to sign-in screen",
    requesterName: "Jennifer Walsh",
    requesterEmail: "j.walsh@kkr.com",
    requesterOrg: "KKR & Co.",
    requesterOrgType: "GP",
    createdAt: "2026-03-19T14:30:00Z",
    updatedAt: "2026-03-20T08:45:00Z",
    assignedTo: "Esteban Fernandez",
    surveyId: "survey-001",
    tags: ["sso", "login-loop"],
    messages: [
      {
        id: "msg-0002-1",
        author: "Jennifer Walsh",
        role: "requester",
        body: "Every time I try to sign in through our company SSO, it redirects me back to the login page without any error message. I've tried two different browsers. This has been happening for 2 days.",
        timestamp: "2026-03-19T14:30:00Z",
        isInternalNote: false,
      },
      {
        id: "msg-0002-2",
        author: "Esteban Fernandez",
        role: "admin",
        body: "Hi Jennifer — I've seen this before with SSO configurations. Can you try clearing cookies and cache, then attempting in an incognito window? Also, please confirm you're signing in with j.walsh@kkr.com and not a personal address.",
        timestamp: "2026-03-19T16:10:00Z",
        isInternalNote: false,
      },
      {
        id: "msg-0002-3",
        author: "Esteban Fernandez",
        role: "admin",
        body: "Escalated to tech team — KKR SSO metadata may have rotated. Awaiting confirmation from their IT. Expected resolution 24–48 hours.",
        timestamp: "2026-03-20T08:45:00Z",
        isInternalNote: true,
      },
    ],
  },
  {
    id: "TKT-0003",
    type: "Permissions",
    status: "Awaiting Response",
    priority: "High",
    subject: "My account shows wrong role — listed as LP not GP",
    requesterName: "Robert Kim",
    requesterEmail: "r.kim@apollo.com",
    requesterOrg: "Apollo Global Management",
    requesterOrgType: "GP",
    createdAt: "2026-03-18T11:00:00Z",
    updatedAt: "2026-03-19T09:20:00Z",
    assignedTo: "Esteban Fernandez",
    surveyId: "survey-002",
    tags: ["wrong-role", "permissions"],
    messages: [
      {
        id: "msg-0003-1",
        author: "Robert Kim",
        role: "requester",
        body: "When I log in, my dashboard shows LP-style view with no survey to complete. We are a GP and should have been invited. Can you fix this?",
        timestamp: "2026-03-18T11:00:00Z",
        isInternalNote: false,
      },
      {
        id: "msg-0003-2",
        author: "Esteban Fernandez",
        role: "admin",
        body: "Hi Robert — I've corrected your account role to GP and linked you to the 2026 DEI Survey. You should now see your survey in the dashboard. Could you log out, clear your session, and log back in to confirm?",
        timestamp: "2026-03-18T13:45:00Z",
        isInternalNote: false,
      },
      {
        id: "msg-0003-3",
        author: "Esteban Fernandez",
        role: "admin",
        body: "Waiting on Robert to confirm fix. If no response by EOD tomorrow, follow up and close.",
        timestamp: "2026-03-19T09:20:00Z",
        isInternalNote: true,
      },
    ],
  },
  {
    id: "TKT-0004",
    type: "Permissions",
    status: "New",
    priority: "High",
    subject: "Entire team locked out since password reset",
    requesterName: "Nicole Brown",
    requesterEmail: "n.brown@vistaequitypartners.com",
    requesterOrg: "Vista Equity Partners",
    requesterOrgType: "GP",
    createdAt: "2026-03-21T07:55:00Z",
    updatedAt: "2026-03-21T07:55:00Z",
    assignedTo: null,
    surveyId: "survey-001",
    tags: ["lockout", "password-reset", "urgent"],
    messages: [
      {
        id: "msg-0004-1",
        author: "Nicole Brown",
        role: "requester",
        body: "Our entire team of 4 people can no longer access the platform since we did a company-wide password reset last Friday. All accounts are showing 'invalid credentials'. The survey deadline is coming up and we haven't been able to start. Please help urgently.",
        timestamp: "2026-03-21T07:55:00Z",
        isInternalNote: false,
      },
    ],
  },
  {
    id: "TKT-0005",
    type: "Permissions",
    status: "In Review",
    priority: "High",
    subject: "Survey link says 'You are not authorized to view this page'",
    requesterName: "Amanda Torres",
    requesterEmail: "a.torres@carlyle.com",
    requesterOrg: "The Carlyle Group",
    requesterOrgType: "GP",
    createdAt: "2026-03-20T16:20:00Z",
    updatedAt: "2026-03-21T10:00:00Z",
    assignedTo: "Esteban Fernandez",
    surveyId: "survey-002",
    tags: ["unauthorized", "survey-link"],
    messages: [
      {
        id: "msg-0005-1",
        author: "Amanda Torres",
        role: "requester",
        body: "The link in the invitation email takes me to an 'You are not authorized' page. I've forwarded this email to two colleagues and they get the same error. Our org is definitely invited — I checked with our LP.",
        timestamp: "2026-03-20T16:20:00Z",
        isInternalNote: false,
      },
      {
        id: "msg-0005-2",
        author: "Esteban Fernandez",
        role: "admin",
        body: "Hi Amanda — looking into this now. The invitation was sent to a.torres@carlylegroup.com (old domain) instead of a.torres@carlyle.com. I'll resend to the correct address right away.",
        timestamp: "2026-03-21T09:30:00Z",
        isInternalNote: false,
      },
      {
        id: "msg-0005-3",
        author: "Esteban Fernandez",
        role: "admin",
        body: "Email domain mismatch — old domain in our system. Updated all 3 Carlyle contacts to @carlyle.com. New invitations sent.",
        timestamp: "2026-03-21T10:00:00Z",
        isInternalNote: true,
      },
    ],
  },

  // ── Access / Survey Link (3 × Medium) ────────────────────────────────────
  {
    id: "TKT-0006",
    type: "Access",
    status: "New",
    priority: "Medium",
    subject: "Where do I find the survey link? Email expired",
    requesterName: "Chris Lee",
    requesterEmail: "c.lee@tpg.com",
    requesterOrg: "TPG Capital",
    requesterOrgType: "GP",
    createdAt: "2026-03-21T09:45:00Z",
    updatedAt: "2026-03-21T09:45:00Z",
    assignedTo: null,
    surveyId: "survey-001",
    tags: ["expired-link", "access"],
    messages: [
      {
        id: "msg-0006-1",
        author: "Chris Lee",
        role: "requester",
        body: "I received an invitation email a few weeks ago but didn't get around to it. Now the link in the email says it's expired. How do I get a new link to start the survey?",
        timestamp: "2026-03-21T09:45:00Z",
        isInternalNote: false,
      },
    ],
  },
  {
    id: "TKT-0007",
    type: "Access",
    status: "Awaiting Response",
    priority: "Medium",
    subject: "Survey invitation not in inbox — checked spam folder",
    requesterName: "Lisa Park",
    requesterEmail: "l.park@warburgpincus.com",
    requesterOrg: "Warburg Pincus",
    requesterOrgType: "GP",
    createdAt: "2026-03-17T13:00:00Z",
    updatedAt: "2026-03-18T11:30:00Z",
    assignedTo: "Esteban Fernandez",
    surveyId: "survey-001",
    tags: ["missing-email", "invitation"],
    messages: [
      {
        id: "msg-0007-1",
        author: "Lisa Park",
        role: "requester",
        body: "I was told by our LP that they sent a DEI survey invitation to me, but I cannot find it anywhere — not in inbox, not in spam. My email is l.park@warburgpincus.com. Can you resend?",
        timestamp: "2026-03-17T13:00:00Z",
        isInternalNote: false,
      },
      {
        id: "msg-0007-2",
        author: "Esteban Fernandez",
        role: "admin",
        body: "Hi Lisa — I've resent the invitation to l.park@warburgpincus.com. You should receive it within a few minutes. If it still doesn't arrive, your firm's email security may be blocking our sending domain. I've CC'd your IT contact on the resend. Let me know once you have it.",
        timestamp: "2026-03-18T10:00:00Z",
        isInternalNote: false,
      },
      {
        id: "msg-0007-3",
        author: "Esteban Fernandez",
        role: "admin",
        body: "Resent twice. No bounce. Likely a corporate firewall issue. Sent direct PDF instructions as backup. Waiting on Lisa to confirm receipt.",
        timestamp: "2026-03-18T11:30:00Z",
        isInternalNote: true,
      },
    ],
  },
  {
    id: "TKT-0008",
    type: "Access",
    status: "Resolved",
    priority: "Medium",
    subject: "Re-send survey access link please",
    requesterName: "Thomas Grant",
    requesterEmail: "t.grant@baincapital.com",
    requesterOrg: "Bain Capital",
    requesterOrgType: "GP",
    createdAt: "2026-03-15T10:00:00Z",
    updatedAt: "2026-03-15T11:45:00Z",
    assignedTo: "Esteban Fernandez",
    surveyId: "survey-002",
    tags: ["resend", "link"],
    messages: [
      {
        id: "msg-0008-1",
        author: "Thomas Grant",
        role: "requester",
        body: "Could you please resend our survey access link? We had a personnel change and the original contact who received it has left the firm.",
        timestamp: "2026-03-15T10:00:00Z",
        isInternalNote: false,
      },
      {
        id: "msg-0008-2",
        author: "Esteban Fernandez",
        role: "admin",
        body: "Hi Thomas — done. I've updated the contact on file to t.grant@baincapital.com and sent a fresh invitation link. The link is valid for 72 hours. Welcome to the process!",
        timestamp: "2026-03-15T11:00:00Z",
        isInternalNote: false,
      },
      {
        id: "msg-0008-3",
        author: "Thomas Grant",
        role: "requester",
        body: "Got it, thank you! Everything is working now.",
        timestamp: "2026-03-15T11:45:00Z",
        isInternalNote: false,
      },
    ],
  },

  // ── LPI Score Confusion (4 × Medium) ─────────────────────────────────────
  {
    id: "TKT-0009",
    type: "Data",
    status: "New",
    priority: "Medium",
    subject: "What does an LPI score of 4.2 mean for our firm?",
    requesterName: "Sarah Okafor",
    requesterEmail: "s.okafor@adventinternational.com",
    requesterOrg: "Advent International",
    requesterOrgType: "GP",
    createdAt: "2026-03-22T08:30:00Z",
    updatedAt: "2026-03-22T08:30:00Z",
    assignedTo: null,
    surveyId: "survey-001",
    tags: ["lpi-score", "benchmarking"],
    messages: [
      {
        id: "msg-0009-1",
        author: "Sarah Okafor",
        role: "requester",
        body: "We received our report and it shows an LPI score of 4.2 out of 10. Is that good or bad? How do we interpret this relative to other firms? Our LP seems concerned about it.",
        timestamp: "2026-03-22T08:30:00Z",
        isInternalNote: false,
      },
    ],
  },
  {
    id: "TKT-0010",
    type: "Data",
    status: "In Review",
    priority: "Medium",
    subject: "LPI sub-components — what exactly is the Ownership Score?",
    requesterName: "Marcus Webb",
    requesterEmail: "m.webb@generalatlantic.com",
    requesterOrg: "General Atlantic",
    requesterOrgType: "GP",
    createdAt: "2026-03-21T15:00:00Z",
    updatedAt: "2026-03-22T09:00:00Z",
    assignedTo: "Esteban Fernandez",
    surveyId: "survey-001",
    tags: ["lpi-components", "ownership"],
    messages: [
      {
        id: "msg-0010-1",
        author: "Marcus Webb",
        role: "requester",
        body: "In our report there are three sub-scores: Ownership, Leadership, and Workforce. I understand Leadership and Workforce, but I'm not sure what Ownership refers to. Does it mean the GPs who own the fund, or something else?",
        timestamp: "2026-03-21T15:00:00Z",
        isInternalNote: false,
      },
      {
        id: "msg-0010-2",
        author: "Esteban Fernandez",
        role: "admin",
        body: "Great question Marcus. Ownership refers specifically to the equity stakeholders in the management company — partners or principals who hold ownership stakes. This is distinct from employees (Workforce) and people in senior management roles (Leadership). Someone can appear in multiple categories if applicable.",
        timestamp: "2026-03-22T09:00:00Z",
        isInternalNote: false,
      },
    ],
  },
  {
    id: "TKT-0011",
    type: "Data",
    status: "Awaiting Response",
    priority: "Medium",
    subject: "Confused about the Gender vs. Racial LPI breakdown",
    requesterName: "Diana Chen",
    requesterEmail: "d.chen@franciscopartners.com",
    requesterOrg: "Francisco Partners",
    requesterOrgType: "GP",
    createdAt: "2026-03-19T12:00:00Z",
    updatedAt: "2026-03-20T14:00:00Z",
    assignedTo: "Esteban Fernandez",
    surveyId: "survey-002",
    tags: ["lpi-breakdown", "gender", "racial"],
    messages: [
      {
        id: "msg-0011-1",
        author: "Diana Chen",
        role: "requester",
        body: "Our report shows a Gender LPI and a Racial LPI separately. How are these weighted in the overall LPI score? Is gender weighted more heavily than racial diversity?",
        timestamp: "2026-03-19T12:00:00Z",
        isInternalNote: false,
      },
      {
        id: "msg-0011-2",
        author: "Esteban Fernandez",
        role: "admin",
        body: "Hi Diana — the Gender LPI and Racial LPI are weighted equally at 50% each in the composite LPI score. Within each dimension, Ownership (30%), Leadership (30%), and Workforce (40%) are weighted as shown in the methodology guide. I'm attaching the full scoring methodology document — let me know if you have follow-up questions.",
        timestamp: "2026-03-20T10:30:00Z",
        isInternalNote: false,
      },
      {
        id: "msg-0011-3",
        author: "Esteban Fernandez",
        role: "admin",
        body: "Sent methodology PDF. Waiting for Diana to confirm she received it and whether her question is resolved.",
        timestamp: "2026-03-20T14:00:00Z",
        isInternalNote: true,
      },
    ],
  },
  {
    id: "TKT-0012",
    type: "Data",
    status: "Resolved",
    priority: "Medium",
    subject: "How is our benchmark pool determined?",
    requesterName: "James Patel",
    requesterEmail: "j.patel@silverlake.com",
    requesterOrg: "Silver Lake Partners",
    requesterOrgType: "GP",
    createdAt: "2026-03-14T09:00:00Z",
    updatedAt: "2026-03-14T16:00:00Z",
    assignedTo: "Esteban Fernandez",
    surveyId: "survey-001",
    tags: ["benchmark-pool", "peer-group"],
    messages: [
      {
        id: "msg-0012-1",
        author: "James Patel",
        role: "requester",
        body: "Our report shows we're in the 'Private Equity' asset class benchmark pool with n=89 managers. Who determines which pool we're in, and can we request a different peer group?",
        timestamp: "2026-03-14T09:00:00Z",
        isInternalNote: false,
      },
      {
        id: "msg-0012-2",
        author: "Esteban Fernandez",
        role: "admin",
        body: "Hi James — pool membership is set at survey close based on the primary strategy you reported (Private Equity in your case), your AUM tier, and geography. It's determined by our methodology team and is consistent for all firms. Firms cannot self-select their peer group to ensure integrity. That said, you can see Universe and Portfolio benchmarks alongside the asset class pool in your report.",
        timestamp: "2026-03-14T13:00:00Z",
        isInternalNote: false,
      },
      {
        id: "msg-0012-3",
        author: "James Patel",
        role: "requester",
        body: "That makes sense, thank you for the thorough explanation. We're comfortable with the methodology.",
        timestamp: "2026-03-14T16:00:00Z",
        isInternalNote: false,
      },
    ],
  },

  // ── Deadline Questions (3 × Low) ──────────────────────────────────────────
  {
    id: "TKT-0013",
    type: "Survey Help",
    status: "New",
    priority: "Low",
    subject: "Is the close date hard or soft?",
    requesterName: "Priya Nair",
    requesterEmail: "p.nair@insightpartners.com",
    requesterOrg: "Insight Partners",
    requesterOrgType: "GP",
    createdAt: "2026-03-22T11:00:00Z",
    updatedAt: "2026-03-22T11:00:00Z",
    assignedTo: null,
    surveyId: "survey-001",
    tags: ["deadline", "close-date"],
    messages: [
      {
        id: "msg-0013-1",
        author: "Priya Nair",
        role: "requester",
        body: "The survey shows a close date of April 30, 2026. Is that a hard deadline or can submissions still be accepted after that date? We have some team members traveling in late April.",
        timestamp: "2026-03-22T11:00:00Z",
        isInternalNote: false,
      },
    ],
  },
  {
    id: "TKT-0014",
    type: "Survey Help",
    status: "In Review",
    priority: "Low",
    subject: "Requesting deadline extension — team unavailable in April",
    requesterName: "Kevin O'Brien",
    requesterEmail: "k.obrien@thomabravo.com",
    requesterOrg: "Thoma Bravo",
    requesterOrgType: "GP",
    createdAt: "2026-03-20T14:00:00Z",
    updatedAt: "2026-03-21T08:00:00Z",
    assignedTo: "Esteban Fernandez",
    surveyId: "survey-001",
    tags: ["extension", "deadline"],
    messages: [
      {
        id: "msg-0014-1",
        author: "Kevin O'Brien",
        role: "requester",
        body: "Our HR team, who owns this survey, will be largely unavailable from April 15–28 due to an internal offsite and quarterly close. Is there any possibility of a 2-week extension beyond April 30?",
        timestamp: "2026-03-20T14:00:00Z",
        isInternalNote: false,
      },
      {
        id: "msg-0014-2",
        author: "Esteban Fernandez",
        role: "admin",
        body: "Hi Kevin — I've noted your request and will check with the LP on whether a short extension is possible. You'll hear back from me within 2 business days. In the meantime, please try to complete as many sections as possible before April 15 — submissions are auto-saved.",
        timestamp: "2026-03-21T07:00:00Z",
        isInternalNote: false,
      },
      {
        id: "msg-0014-3",
        author: "Esteban Fernandez",
        role: "admin",
        body: "Confirmed with LP: hard close is April 30. No extensions available this cycle. Need to communicate this to Kevin today.",
        timestamp: "2026-03-21T08:00:00Z",
        isInternalNote: true,
      },
    ],
  },
  {
    id: "TKT-0015",
    type: "Survey Help",
    status: "Resolved",
    priority: "Low",
    subject: "Please confirm our survey window and deadline",
    requesterName: "Astrid Lindqvist",
    requesterEmail: "a.lindqvist@nordiccapital.com",
    requesterOrg: "Nordic Capital",
    requesterOrgType: "GP",
    createdAt: "2026-03-12T10:00:00Z",
    updatedAt: "2026-03-12T13:00:00Z",
    assignedTo: "Esteban Fernandez",
    surveyId: "survey-002",
    tags: ["survey-window", "deadline"],
    messages: [
      {
        id: "msg-0015-1",
        author: "Astrid Lindqvist",
        role: "requester",
        body: "Could you confirm the exact open and close dates for our survey? We want to put it on our internal calendar.",
        timestamp: "2026-03-12T10:00:00Z",
        isInternalNote: false,
      },
      {
        id: "msg-0015-2",
        author: "Esteban Fernandez",
        role: "admin",
        body: "Hi Astrid — your survey (2025 Lenox Park DEI Survey) is open from January 15, 2026 through March 31, 2026. You have access to submit or amend responses any time within that window. Your current status shows as In Progress.",
        timestamp: "2026-03-12T13:00:00Z",
        isInternalNote: false,
      },
      {
        id: "msg-0015-3",
        author: "Astrid Lindqvist",
        role: "requester",
        body: "Perfect, thank you — added to our calendar.",
        timestamp: "2026-03-12T13:45:00Z",
        isInternalNote: false,
      },
    ],
  },

  // ── Data Upload (3 × Medium) ──────────────────────────────────────────────
  {
    id: "TKT-0016",
    type: "Survey Help",
    status: "New",
    priority: "Medium",
    subject: "What file format do you accept for policy document upload?",
    requesterName: "David Kim",
    requesterEmail: "d.kim@aresmgmt.com",
    requesterOrg: "Ares Management",
    requesterOrgType: "GP",
    createdAt: "2026-03-22T13:00:00Z",
    updatedAt: "2026-03-22T13:00:00Z",
    assignedTo: null,
    surveyId: "survey-001",
    tags: ["file-upload", "policy-docs"],
    messages: [
      {
        id: "msg-0016-1",
        author: "David Kim",
        role: "requester",
        body: "We're ready to upload our DEI policy documents in the final section of the survey. What file types and size limits do you accept? We have a 45MB PDF.",
        timestamp: "2026-03-22T13:00:00Z",
        isInternalNote: false,
      },
    ],
  },
  {
    id: "TKT-0017",
    type: "Survey Help",
    status: "Awaiting Response",
    priority: "Medium",
    subject: "Upload button is grayed out — cannot submit policy documents",
    requesterName: "Rachel Thompson",
    requesterEmail: "r.thompson@harbourvest.com",
    requesterOrg: "HarbourVest Partners",
    requesterOrgType: "GP",
    createdAt: "2026-03-21T16:00:00Z",
    updatedAt: "2026-03-22T09:30:00Z",
    assignedTo: "Esteban Fernandez",
    surveyId: "survey-001",
    tags: ["upload-button", "disabled"],
    messages: [
      {
        id: "msg-0017-1",
        author: "Rachel Thompson",
        role: "requester",
        body: "I'm on the final section of the survey and the 'Upload Documents' button appears grayed out and unclickable. I've tried refreshing the page. Is there something I need to complete first?",
        timestamp: "2026-03-21T16:00:00Z",
        isInternalNote: false,
      },
      {
        id: "msg-0017-2",
        author: "Esteban Fernandez",
        role: "admin",
        body: "Hi Rachel — the upload section unlocks only after Sections 1, 2, and 3 (Ownership, Leadership, Workforce) have been saved. Our system shows Section 2 (Leadership) has no data entered yet. Once you complete and save that section, the upload button will activate automatically.",
        timestamp: "2026-03-22T09:00:00Z",
        isInternalNote: false,
      },
      {
        id: "msg-0017-3",
        author: "Esteban Fernandez",
        role: "admin",
        body: "Leadership section incomplete — that's why upload is locked. Sent explanation. Waiting for Rachel to confirm.",
        timestamp: "2026-03-22T09:30:00Z",
        isInternalNote: true,
      },
    ],
  },
  {
    id: "TKT-0018",
    type: "Survey Help",
    status: "Resolved",
    priority: "Medium",
    subject: "Workforce headcount — do contractors count?",
    requesterName: "Patricia Moore",
    requesterEmail: "p.moore@hamiltonlane.com",
    requesterOrg: "Hamilton Lane",
    requesterOrgType: "GP",
    createdAt: "2026-03-13T11:30:00Z",
    updatedAt: "2026-03-13T15:00:00Z",
    assignedTo: "Esteban Fernandez",
    surveyId: "survey-002",
    tags: ["headcount", "contractors", "methodology"],
    messages: [
      {
        id: "msg-0018-1",
        author: "Patricia Moore",
        role: "requester",
        body: "For the Workforce Diversity section, should we include independent contractors and consultants in our headcount numbers? We have about 40 long-term contractors embedded in our teams.",
        timestamp: "2026-03-13T11:30:00Z",
        isInternalNote: false,
      },
      {
        id: "msg-0018-2",
        author: "Esteban Fernandez",
        role: "admin",
        body: "Hi Patricia — contractors and consultants should be excluded from the Workforce section. Please include only full-time and part-time direct employees as of your most recent fiscal year-end. If a contractor works exclusively for your firm under a direct services agreement, you may include them at your discretion, but it is not required. Interns should also be excluded.",
        timestamp: "2026-03-13T14:00:00Z",
        isInternalNote: false,
      },
      {
        id: "msg-0018-3",
        author: "Patricia Moore",
        role: "requester",
        body: "Very helpful, thank you. We'll exclude contractors and proceed with direct employees only.",
        timestamp: "2026-03-13T15:00:00Z",
        isInternalNote: false,
      },
    ],
  },

  // ── Other (2) ─────────────────────────────────────────────────────────────
  {
    id: "TKT-0019",
    type: "Other",
    status: "In Review",
    priority: "Medium",
    subject: "Who has access to our submitted data? Privacy concern",
    requesterName: "Leon Foster",
    requesterEmail: "l.foster@nb.com",
    requesterOrg: "Neuberger Berman",
    requesterOrgType: "GP",
    createdAt: "2026-03-21T10:00:00Z",
    updatedAt: "2026-03-21T14:00:00Z",
    assignedTo: "Esteban Fernandez",
    surveyId: null,
    tags: ["privacy", "data-security"],
    messages: [
      {
        id: "msg-0019-1",
        author: "Leon Foster",
        role: "requester",
        body: "Before we submit our data, I want to understand who can see our raw demographic numbers. Can other GPs in the survey see our firm's data? Does Roundtables sell or share this data with third parties?",
        timestamp: "2026-03-21T10:00:00Z",
        isInternalNote: false,
      },
      {
        id: "msg-0019-2",
        author: "Esteban Fernandez",
        role: "admin",
        body: "Hi Leon — your data is strictly confidential. No other GP can see your firm's raw data. Roundtables only shares aggregated, anonymized benchmark statistics. Your LP receives your LPI score and percentile ranking, but not your underlying demographic counts. We do not sell data to any third parties. I'll send over our data privacy policy document for your review.",
        timestamp: "2026-03-21T13:30:00Z",
        isInternalNote: false,
      },
      {
        id: "msg-0019-3",
        author: "Esteban Fernandez",
        role: "admin",
        body: "Privacy policy sent. Leon may want us to counter-sign an NDA — check with legal if he requests that.",
        timestamp: "2026-03-21T14:00:00Z",
        isInternalNote: true,
      },
    ],
  },
  {
    id: "TKT-0020",
    type: "Other",
    status: "Awaiting Response",
    priority: "Low",
    subject: "How do we update our primary contact person on file?",
    requesterName: "Yuki Tanaka",
    requesterEmail: "y.tanaka@stepstonegroup.com",
    requesterOrg: "StepStone Group",
    requesterOrgType: "GP",
    createdAt: "2026-03-20T09:00:00Z",
    updatedAt: "2026-03-20T12:00:00Z",
    assignedTo: "Esteban Fernandez",
    surveyId: null,
    tags: ["contact-update", "account"],
    messages: [
      {
        id: "msg-0020-1",
        author: "Yuki Tanaka",
        role: "requester",
        body: "We recently promoted our Head of HR and she will now be handling this survey going forward. How do I update the primary contact in our Roundtables account so future surveys go to her instead of me?",
        timestamp: "2026-03-20T09:00:00Z",
        isInternalNote: false,
      },
      {
        id: "msg-0020-2",
        author: "Esteban Fernandez",
        role: "admin",
        body: "Hi Yuki — congratulations on the promotion within your team! To update the primary contact, please reply with your new contact's name, email address, and title and I'll update it in the system right away.",
        timestamp: "2026-03-20T11:00:00Z",
        isInternalNote: false,
      },
      {
        id: "msg-0020-3",
        author: "Esteban Fernandez",
        role: "admin",
        body: "Waiting on new contact details from Yuki. Follow up if no response by end of week.",
        timestamp: "2026-03-20T12:00:00Z",
        isInternalNote: true,
      },
    ],
  },
];

// ─── Templates ────────────────────────────────────────────────────────────────

export const MOCK_TEMPLATES: QuickReplyTemplate[] = [
  // Permissions & Access
  {
    id: "tmpl-01",
    category: "Permissions & Access",
    title: "Role Correction Confirmation",
    preview: "Confirms the user's role has been corrected and access restored.",
    body: "Hi {{firstName}},\n\nI've corrected your role assignment in the system — you should now have full access to your survey. Please clear your browser cache and try the link again.\n\nLet me know if you encounter any further issues.\n\n— Esteban",
  },
  {
    id: "tmpl-02",
    category: "Permissions & Access",
    title: "New Invitation Link",
    preview: "Sends a fresh invitation link when the original has expired.",
    body: "Hi {{firstName}},\n\nI've generated a new survey access link for you:\n\n{{surveyLink}}\n\nThis link is valid for 72 hours. If you continue to experience issues, please reply with the exact error message you see.\n\n— Esteban",
  },
  {
    id: "tmpl-03",
    category: "Permissions & Access",
    title: "SSO Troubleshooting Steps",
    preview: "Step-by-step SSO fix for users looping on the login screen.",
    body: "Hi {{firstName}},\n\nIf you're experiencing a login loop, please try these steps:\n\n1. Clear cookies and cache in your browser\n2. Try an incognito / private browsing window\n3. Ensure you're signing in with your firm email ({{email}}), not a personal address\n4. If using a password manager, try entering credentials manually\n\nIf none of these resolve the issue, please reply here and I'll escalate to our technical team.\n\n— Esteban",
  },

  // Survey Completion
  {
    id: "tmpl-04",
    category: "Survey Completion",
    title: "How to Navigate the Survey",
    preview: "Guides a GP through the four main survey sections.",
    body: "Hi {{firstName}},\n\nThe DEI survey has four main sections:\n\n1. Ownership Data — equity stakeholders in the management company\n2. Leadership Data — C-suite and Managing Directors\n3. Workforce Diversity — all full-time and part-time employees\n4. Policy Upload — optional DEI policy documents\n\nYou can save your progress at any time and return later — data is auto-saved every 30 seconds. The Walkthrough guide in our Support Hub has step-by-step screenshots.\n\n— Esteban",
  },
  {
    id: "tmpl-05",
    category: "Survey Completion",
    title: "Definition of Covered Employees",
    preview: "Clarifies which employees count for workforce diversity data.",
    body: "Hi {{firstName}},\n\nFor the Workforce section, please include all full-time and part-time direct employees as of your most recent fiscal year-end.\n\nExclude:\n• Independent contractors and consultants\n• Interns and temporary workers\n• Employees from portfolio companies\n\nIf a specific employee category is unclear, please describe it and I'll advise.\n\n— Esteban",
  },
  {
    id: "tmpl-06",
    category: "Survey Completion",
    title: "Policy Upload Instructions",
    preview: "Explains accepted file formats and how the upload step unlocks.",
    body: "Hi {{firstName}},\n\nFor the Policy & Documents upload:\n\n• Accepted formats: PDF, DOCX, XLSX (max 25MB per file)\n• You can upload multiple documents\n• The upload button unlocks automatically after Sections 1–3 (Ownership, Leadership, Workforce) are saved\n\nIf the button is still grayed out after completing those sections, try a hard refresh (Ctrl+Shift+R / Cmd+Shift+R).\n\n— Esteban",
  },

  // Data & Benchmarks
  {
    id: "tmpl-07",
    category: "Data & Benchmarks",
    title: "LPI Score Explained",
    preview: "Plain-English explanation of what the LPI score represents.",
    body: "Hi {{firstName}},\n\nThe LPI (LP Inclusion Index) is a 0–10 composite score measuring DEI performance across three dimensions:\n\n• Ownership (30%) — diversity among equity stakeholders\n• Leadership (30%) — diversity among senior management\n• Workforce (40%) — diversity across all employees\n\nThe overall score is split equally between Gender LPI (50%) and Racial LPI (50%). A score of {{lpiScore}} places {{orgName}} at the {{percentile}}th percentile among {{n}} firms in your benchmark pool.\n\n— Esteban",
  },
  {
    id: "tmpl-08",
    category: "Data & Benchmarks",
    title: "Benchmark Pool Membership",
    preview: "Explains how a firm's benchmark peer group is determined.",
    body: "Hi {{firstName}},\n\nYour firm is benchmarked in three pools:\n\n1. Roundtables Universe — all {{universeN}}+ participating firms\n2. LP Portfolio — firms your LP has invested in\n3. Asset Class — firms in your primary strategy ({{assetClass}})\n\nPool membership is determined at survey close based on your reported primary strategy, AUM tier, and geography. Firms cannot self-select their peer group to preserve benchmark integrity.\n\n— Esteban",
  },
  {
    id: "tmpl-09",
    category: "Data & Benchmarks",
    title: "Data Privacy Assurance",
    preview: "Reassures firms that their raw data is never shared with other GPs.",
    body: "Hi {{firstName}},\n\nYour submitted data is strictly confidential. Here's how it's protected:\n\n• No other GP can see your firm's raw demographic data\n• Your LP receives only your LPI score and percentile — not underlying counts\n• Roundtables does not sell or share raw data with any third parties\n• All benchmark statistics shared with LPs are aggregated and anonymized\n\nI'm happy to provide our full data privacy policy document on request.\n\n— Esteban",
  },

  // Status Updates
  {
    id: "tmpl-10",
    category: "Status Updates",
    title: "Survey Still Open — Confirmation",
    preview: "Confirms the survey is still accepting submissions with deadline.",
    body: "Hi {{firstName}},\n\nThe {{surveyName}} survey is currently open and accepting submissions until {{closeDate}}. You have {{daysRemaining}} days remaining.\n\nYour current status shows as: {{status}}\n\nIf you need additional time, please let me know as early as possible and I'll see what we can do.\n\n— Esteban",
  },
  {
    id: "tmpl-11",
    category: "Status Updates",
    title: "Report Delivery Timeline",
    preview: "Sets expectations for when the LP report will be published.",
    body: "Hi {{firstName}},\n\nLPI reports are typically published within 4–6 weeks after the survey closes. Once your report is ready, you'll receive an email with a secure link to view it in your Roundtables dashboard.\n\nThe current survey closes on {{closeDate}}, so you can expect your report around {{reportETA}}.\n\nIf you need an interim update, feel free to reply here.\n\n— Esteban",
  },
  {
    id: "tmpl-12",
    category: "Status Updates",
    title: "Extension Request Acknowledgment",
    preview: "Acknowledges a deadline extension request and sets next steps.",
    body: "Hi {{firstName}},\n\nThank you for reaching out about a deadline extension for {{orgName}}. I've noted your request and will confirm with the LP whether an extension is possible. You'll hear back from me within 2 business days.\n\nIn the meantime, I'd encourage you to complete as many sections as possible before your team becomes unavailable — all progress is auto-saved and you can resume at any time.\n\n— Esteban",
  },
];

// ─── Walkthrough Steps ────────────────────────────────────────────────────────

export const MOCK_WALKTHROUGH_STEPS: WalkthroughStep[] = [
  {
    stepNumber: 1,
    title: "Log In & Locate Your Survey",
    subtitle: "Finding your invitation and accessing the platform",
    guidanceText:
      "You'll receive an email invitation from noreply@roundtables.com with a unique access link. Click the link, sign in with your firm email address via SSO or password, and you'll land directly on your survey dashboard. If your link has expired, contact your LP administrator for a new one.",
    visualType: "survey-locator",
  },
  {
    stepNumber: 2,
    title: "Understand the LPI Framework",
    subtitle: "What the survey measures and how scoring works",
    guidanceText:
      "The LP Inclusion Index (LPI) scores your firm across three dimensions: Ownership (equity holders), Leadership (C-suite and Managing Directors), and Workforce (all employees). Scores range from 0 to 10 and are split equally between Gender and Racial diversity. Higher scores reflect greater representation at each level.",
    visualType: "lpi-explainer",
  },
  {
    stepNumber: 3,
    title: "Complete Ownership Data",
    subtitle: "Report gender and racial breakdown of equity owners",
    guidanceText:
      "In the Ownership section, list all individuals who hold an equity stake in the fund or management company. For each person, select their gender identity and racial/ethnic category from the provided dropdowns. Use your most recent fiscal year-end data. If an owner holds a stake in multiple funds, count them once.",
    visualType: "ownership-form",
  },
  {
    stepNumber: 4,
    title: "Complete Leadership Data",
    subtitle: "Report diversity among C-suite and Managing Directors",
    guidanceText:
      "Leadership includes all C-suite officers (CEO, CFO, COO, CIO) and Managing Directors or equivalent senior roles. Use the same fiscal year-end date as Ownership. If a person appears in both Ownership and Leadership, include them in both sections — they are counted separately for scoring.",
    visualType: "leadership-form",
  },
  {
    stepNumber: 5,
    title: "Complete Workforce Diversity",
    subtitle: "Report headcount by gender and race across all employees",
    guidanceText:
      "Workforce data covers all full-time and part-time employees, excluding contractors and interns. Enter headcount totals by gender (Men / Women / Non-binary / Prefer not to say) and by race/ethnicity using the eight EEOC-aligned categories provided. Use your most recent fiscal year-end payroll data.",
    visualType: "workforce-form",
  },
  {
    stepNumber: 6,
    title: "Upload Policies & Submit",
    subtitle: "Attach your DEI policies and finalize your submission",
    guidanceText:
      "In the final step, upload any DEI-related policy documents (PDF or DOCX, max 25MB each). This is optional but improves your completeness score. Once you've reviewed all sections, click 'Submit Survey'. You'll receive a confirmation email within minutes. Submissions can be amended up until the survey close date.",
    visualType: "upload-submit",
  },
];

// ─── Helper Functions ─────────────────────────────────────────────────────────

export function getTicketById(id: string): SupportTicket | undefined {
  return MOCK_TICKETS.find((t) => t.id === id);
}

export function getTicketsByStatus(status: TicketStatus): SupportTicket[] {
  return MOCK_TICKETS.filter((t) => t.status === status);
}

export function getTicketsByType(type: TicketType): SupportTicket[] {
  return MOCK_TICKETS.filter((t) => t.type === type);
}

export function getTemplatesByCategory(category: TemplateCategory): QuickReplyTemplate[] {
  return MOCK_TEMPLATES.filter((t) => t.category === category);
}
